---

- name: Collect IOS facts
  hosts: 192.168.100.100

  tasks:

    - name: Configure vlans
      ios_vlans:
        config:
          - name: Vlan_10
            vlan_id: 10
          - name: Vlan_20
            vlan_id: 20
        state: merged
      register: result

    - name: Show result
      debug: var=result

