---

- name: Collect IOS facts
  hosts: cisco_routers

  tasks:

    - name: Facts
      ios_facts:
        gather_subset: all

    - name: debug
      debug: var=ansible_net_interfaces['Ethernet0/1']
