---

- name: Run cfg commands on routers
  hosts: 192.168.100.1

  tasks:

    - name: Send config commands
      ios_config:
        commands:
          - service password-encryption
          - no ip http server
          - no ip http secure-server
          - no ip domain lookup
