---

- name: Run cfg commands on router
  hosts: cisco_routers

  tasks:

    - name: Facts
      ios_facts:
        gather_subset: interfaces

    - name: Config OSPF
      ios_config:
        src: templates/ospf2.j2
